### ISSUE TITLE
Viewing an app gives ingress error

### ISSUE THREAD

**Issue by davidread** [ministryofjustice/analytics-platform-control-panel#677]
Viewing any app in dev cpanel gives an error: https://cpanel-master.services.dev.mojanalytics.xyz/apps/11

> Found 0 ingresses for app kpi-s3-proxy
> Error: Found 0 ingresses for app kpi-s3-proxy

<img width="724" alt="Screen Shot 2019-05-22 at 08 53 53" src="https://user-images.githubusercontent.com/307612/58157044-0b071500-7c67-11e9-8214-3561a7d7c50c.png">

**Comment by andyhd** [comment]
This issue belongs in https://github.com/ministryofjustice/analytics-platform-control-panel-frontend, but I think it is fixed already anyway

**Comment by andyhd** [comment]
Moved to https://github.com/ministryofjustice/analytics-platform-control-panel-frontend/issues/416
